### ISSUE TITLE
Handler doesn't work with chat_id only with channel_name

### ISSUE THREAD

**Issue by andreydayen** [guyshe/telegram_handler#10]
Hi!

The handler returns 400 error when using chat id instead of channel name.
You need not to hardcode '@' in API_URL in consts.py because chat_id=@test_chat is okay same time chat_id=@-123456 won't work.
I propose the change in code (below) and in docs that if you're going to use channel_name than '@' should be provided at init:
API_URL = f'https://{API_HOST}/bot{{bot_token}}/sendMessage?' \
          f'chat_id={{channel_name}}&parse_mode=HTML'

**Comment by guyshe** [comment]
Hey!
Thanks, and sorry for the late response.

I fixed the bug in [release/1.4.4](https://github.com/guyshe/telegram_handler/releases/tag/1.4.4) 
In order to not break the API, I check whether the input is an integer or a string, and then act accordingly.
